# Generated by Django 4.1.6 on 2023-03-20 16:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish", "hit_count_generic__hits"]},
        ),
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("activated", django.db.models.manager.Manager()),
            ],
        ),
    ]
