# Generated by Django 4.1.6 on 2023-03-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_comment_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[],
        ),
    ]
